### ISSUE TITLE
[BUG]: Excavator downgraded a manifest on update

### ISSUE THREAD

**Issue by brian6932** [ScoopInstaller/Excavator#8]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

wordle

### Expected/Current Behaviour

https://github.com/brian6932/dank-scoop/commit/cb9b1341064fa2ed070ddbe49ae72bb7cd16bc0b Not sure what exactly happened here
https://github.com/brian6932/dank-scoop/runs/5767757041#step:3:194

### Steps to Reproduce

```console
I am unable to reproduce locally, however actions did do it. My local checkver does not show such issues.
```

### Possible Solution

Idk, all I can say is that it's not happening locally
![image_196](https://user-images.githubusercontent.com/18603393/161051790-9f050325-f215-48cd-b5df-b72aeba301db.png)

### Scoop and Buckets Version

```console
Current Scoop version:
7d5a47cc (HEAD -> master, origin/master, origin/HEAD) fix(install): Use 'Get-Command' to test scoop install status (#4785)
'dank-scoop' bucket:
835b620 (HEAD -> master, origin/master, origin/HEAD) Revert "wordle: Update to version 0.2.1"
```

### Scoop Config

```console
lastupdate   : 3/31/2022 7:49:11 AM
SCOOP_REPO   : https://github.com/lukesampson/scoop
SCOOP_BRANCH : master
alias        :
debug        : True
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.20152
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
Excavator will always change to the latest version visible on the releases page. So if the new releases were deleted at some point (and restored later), and checkver ran in that time window, the change would be a downgrade instead of upgrade.

**Comment by brian6932** [comment]
So it was deleted? 🤔

**Comment by rashil2000** [comment]
Probably. No way to know.

**Comment by brian6932** [comment]
@rashil2000 I had this happen again
Here: https://github.com/brian6932/dank-scoop/commit/bef1013aa362e57c448554975c9b3209a677b367
Actions: https://github.com/brian6932/dank-scoop/runs/5845126541#step:3:194
[It did revert itself again](https://github.com/brian6932/dank-scoop/commit/18f0c516f749eafedac8aa8d7e0b834083c73c05), but this just being a coincidence is kinda sus

**Comment by rashil2000** [comment]
Could you ask in the source repo to confirm that releases aren't being modified?

**Comment by brian6932** [comment]
@rashil2000 it has not been modified in over a year
https://github.com/jsoncomma/jsoncomma/issues/5#issuecomment-1090942212

**Comment by rashil2000** [comment]
Interesting. I'm confused too, as to what the GitHub Actions runner is seeing as the latest release.
